### ISSUE TITLE
App is showing extensions that are not currently used by the published sheet

### ISSUE THREAD

**Issue by steveonabike** [eapowertools/qs-extension-usage-dashboard#7] opened 2020-06-17 20:25 UTC
Hello, 

This app is going to be great and extremely useful so thanks for pulling it together. 

We noticed that it's showing many extensions that are not being used in a given app/sheet. 

Thinking that maybe some date or flag needs to be added to the telemetry metadata generator and then added to the extension usage data model to cull the unused extensions out. Here are some details in an example. 

Thanks! 
[The Extension Usage Dashboard is showing incorrect app to app extension relationships.docx](https://github.com/eapowertools/qs-extension-usage-dashboard/files/4798984/The.Extension.Usage.Dashboard.is.showing.incorrect.app.to.app.extension.relationships.docx)

**Comment by levi-turner** [comment] 2020-06-23 21:06
Hey there,

I'd be curious to know whether this aligns with an issue that I am aware of. Unfortunately since it requires changes to the Telemetry meta-data fetch code I am awaiting a new version of it for a finalized release.

Files: [package.zip](https://github.com/eapowertools/qs-extension-usage-dashboard/files/4821942/package.zip)

Installation description:
- Unzip
- Import new QVF
- Navigate to `Share\TelemetryDashboard\MetadataGenerater\lib` and rename `getAppsEngine.js` to `getAppsEngine-default.js`
- Place `package\getAppsEngine.js` into `Share\TelemetryDashboard\MetadataGenerater\lib`
- Reload _TelemetryDashboard-1-Generate-Metadata_
- Reload `Extension Usage Dashboard - 1.0.0 (Beta) w REST Connector Fix.qvf`

Let me know if that solves it otherwise we'll need to dig in deeper into what the cause is.

**Comment by steveonabike** [comment] 2020-06-30 14:09
Hello Levi, 

I gave the fix a try and unfortunately, it did not work out. The sheet ID I was using as an example which still exists in the environment, has dropped out of the dashboard completely.

**Comment by simonaubertbd** [comment] 2020-10-20 06:39
Hello @levi-turner 

Same issue here. And that's a big one because we are currently removing the old extensions for new native object and this dashoard is the tool we use to control the project. In my opinion as previoulsy discussed, the root is the use of the Telemetry Dashboard. Extension usage must show only the current metadata while TS must show an historical data. Maybe using API instead of logs would solve that?

Best regards,

Simon

**Comment by levi-turner** [comment] 2020-10-29 16:37
Fixed in 2.0.0: https://github.com/eapowertools/qs-extension-usage-dashboard/releases/tag/2.0.0

**Closed as completed by levi-turner** 2020-10-29 16:37 UTC
Labels: bug
